### ISSUE TITLE
Backpack frame strata

### ISSUE THREAD

**Issue by p3lim** [p3lim-wow/LibContainer#16]
# Backpack strata issue with Xloot's loot monitor
## Steps to reproduce
1. Have Xloot installed with the Loot Monitor enabled and placed somewhere the Backpack windows will appear on top.
2. Be in a group and have things show up in the loot monitor, or try the "test" option in the options (YMMV with the latter).
3. Open Backpack.
## Expected outcome
- Backpack should appear above the Loot Monitor.
## Actual outcome
- Some Backpack windows appear above the Loot Monitor strata while some appear below. See attached screenshot. It's a bit hard to see, but Equipment Sets is below the Loot Monitor, while New Items is above.

![image](https://cloud.githubusercontent.com/assets/120364/19826442/467a0262-9d50-11e6-8971-cb1bc5a6de7f.png)

@xtoq

**Comment by p3lim** [comment]
Why would you expect backpack to appear above?

**Comment by p3lim** [comment]
Regardless, it's set to `MEDIUM` because it has to overlap bottom-level things (like the WatchFrame at `LOW`), but not overlap windows (like the character frame at `HIGH`).

It's rather an issue with XLoot, which IMO should set itself to `HIGH` as well, if not `DIALOG`.

**Comment by xtoq** [comment]
I wouldn't expect backpack to appear above, but to have consistent strata with all the windows. Right now it looks like the Equipment window has a different strata than the New Items window, since you can see the bottom half of the XLoot monitor window and not the top half.

I completely understand bringing it up to the XLoot author though; I'll make a ticket there. Thank you!
